#  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓  ┏┓┏┓┏┓┏┳┓
#  ┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃━━┣ ┃┃┃┃ ┃ 
#  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗  ┻ ┗┛┗┛ ┻ 
#                             


# -*- conf -*-
# Matugen

[colors]
alpha=0.9
background=16130b
foreground=eae1d4
regular0=16130b
regular1=ffb4ab
regular2=e5c36c
regular3=aecfac
regular4=ffdf93
regular5=f3e1bb
regular6=d6c5a0
regular7=eae1d4
bright0=3d392f
bright1=ffb4ab
bright2=e5c36c
bright3=aecfac
bright4=ffdf93
bright5=f3e1bb
bright6=d6c5a0
bright7=eae1d4
dim0=45475A 
dim1=F38BA8 
dim2=A6E3A1 
dim3=F9E2AF 
dim4=89B4FA 
dim5=F5C2E7 
dim6=94E2D5 
dim7=BAC2DE 
selection-foreground=e5c36c
selection-background=3e2e00
cursor=4c4639 eae1d4
